<a href="https://colab.research.google.com/github/Akshata123456789/Pandas/blob/main/Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
dict1 ={'Name':['Priyang','Aadhya','Krisha','Vedant','Parshv',
                'Mittal','Archana'],
                'Marks':[98,89,99,87,90,83,99],
                'Gender':['Male','Female','Female','Male','Male',
                         'Female','Female']
               }

In [2]:
import pandas as pd
df=pd.DataFrame(dict1)

In [7]:
df

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2   Krisha     99  Female
3   Vedant     87    Male
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

In [6]:
df.head(3)

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2   Krisha     99  Female

In [7]:
df.tail(3)

      Name  Marks  Gender
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

In [8]:
df.shape

(7, 3)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    7 non-null      object
 1   Marks   7 non-null      int64
 2   Gender  7 non-null      object
dtypes: int64(1), object(2)
memory usage: 300.0+ bytes

In [11]:
df.isnull().sum()

Name      0
Marks     0
Gender    0
dtype: int64

In [13]:
df.describe(include="all")

           Name      Marks  Gender
count         7   7.000000       7
unique        7        NaN       2
top     Priyang        NaN  Female
freq          1        NaN       4
mean        NaN  92.142857     NaN
std         NaN   6.491753     NaN
min         NaN  83.000000     NaN
25%         NaN  88.000000     NaN
50%         NaN  90.000000     NaN
75%         NaN  98.500000     NaN
max         NaN  99.000000     NaN

In [17]:
df['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [18]:
df['Gender'].nunique()

2

In [19]:
df['Gender'].value_counts()

Gender
Female    4
Male      3
Name: count, dtype: int64

In [28]:
df[df['Marks'].between(90,100)]

      Name  Marks  Gender
0  Priyang     98    Male
2   Krisha     99  Female
4   Parshv     90    Male
6  Archana     99  Female

In [35]:
sum(df['Marks'].between(90,100))

4

In [27]:
df[(df['Marks']>= 90) & (df['Marks']<=100)]

      Name  Marks  Gender
0  Priyang     98    Male
2   Krisha     99  Female
4   Parshv     90    Male
6  Archana     99  Female

In [33]:
len(df[(df['Marks']>=90) & (df['Marks']<=100)])

4

In [36]:
df['Marks'].mean()

np.float64(92.14285714285714)

In [37]:
df['Marks'].max()

99

In [38]:
def m1(x):
  return x/2

In [40]:
df['half_marks']=df['Marks'].apply(m1)

In [41]:
df

      Name  Marks  Gender  half_marks
0  Priyang     98    Male        49.0
1   Aadhya     89  Female        44.5
2   Krisha     99  Female        49.5
3   Vedant     87    Male        43.5
4   Parshv     90    Male        45.0
5   Mittal     83  Female        41.5
6  Archana     99  Female        49.5

In [42]:
df['Marks'].apply(lambda x:x/2)

0    49.0
1    44.5
2    49.5
3    43.5
4    45.0
5    41.5
6    49.5
Name: Marks, dtype: float64

In [44]:
df['Male_Female']=df['Gender'].map({'Male':1,'Female':0})

In [45]:
df

      Name  Marks  Gender  half_marks  Male_Female
0  Priyang     98    Male        49.0            1
1   Aadhya     89  Female        44.5            0
2   Krisha     99  Female        49.5            0
3   Vedant     87    Male        43.5            1
4   Parshv     90    Male        45.0            1
5   Mittal     83  Female        41.5            0
6  Archana     99  Female        49.5            0

In [46]:
df.drop(["Male_Female"],axis=1)

      Name  Marks  Gender  half_marks
0  Priyang     98    Male        49.0
1   Aadhya     89  Female        44.5
2   Krisha     99  Female        49.5
3   Vedant     87    Male        43.5
4   Parshv     90    Male        45.0
5   Mittal     83  Female        41.5
6  Archana     99  Female        49.5

In [49]:
df.drop(["Male_Female","half_marks"],axis=1,inplace=True)

In [50]:
df

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2   Krisha     99  Female
3   Vedant     87    Male
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

In [48]:
df.columns

Index(['Name', 'Marks', 'Gender', 'half_marks', 'Male_Female'], dtype='object')

In [4]:
df['Marks'].sort_values(ascending=False)

2    99
6    99
0    98
4    90
1    89
3    87
5    83
Name: Marks, dtype: int64

In [9]:
df.sort_values(by=["Marks","Gender"])

      Name  Marks  Gender
5   Mittal     83  Female
3   Vedant     87    Male
1   Aadhya     89  Female
4   Parshv     90    Male
0  Priyang     98    Male
2   Krisha     99  Female
6  Archana     99  Female

In [1]:
!git clone https://github.com/users/Akshata123456789/projects/4

Cloning into '4'...
remote: Not Found
fatal: repository 'https://github.com/users/Akshata123456789/projects/4/' not found